server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agreement-backend-service
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # prod uchun tavsiya etilmaydi (validate / none yaxshiroq)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: redis-18303.c262.us-east-1-3.ec2.cloud.redislabs.com
      port: 18303
      username: default
      password: "dUKiYkdoqEYboTQGP62aBdmogK6eFZm4"
      timeout: 60000
      ssl:
        enabled: true

security:
  jwt:
    secret-key: "MWIxNzc4NDg0MjMzNDVmZGY4ZjgwZTBkMDU4ZWVjYWNiMTdkZjMwNTJhOTNmNDZiYWVmN2MyOGQyNjQ2MzdiMTc="
    expiration-time: 86400000 # 24 soat (millisekund)

  otp:
    expiration-time: 300      # 5 daqiqa (sekund)
    length: 6
    max-attempts: 3

  sms:
    provider: eskiz           # eskiz | playmobile
    api-url: https://notify.eskiz.uz/api
    api-token: your-eskiz-token
