server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agreement-backend-service
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379


security:
  jwt:
    secret-key: "MWIxNzc4NDg0MjMzNDVmZGY4ZjgwZTBkMDU4ZWVjYWNiMTdkZjMwNTJhOTNmNDZiYWVmN2MyOGQyNjQ2MzdiMTc="
    expiration-time: 86400000

  otp:
    expiration-time: 300
    length: 6
    max-attempts: 3

  sms:
    provider: dev   # dev | eskiz
    api-url: https://notify.eskiz.uz/api

    # Eskiz login (PROD uchun kerak)
    eskiz-email: "YOUR_EMAIL"
    eskiz-password: "YOUR_PASSWORD"

    # Eskiz sender (kabinetdan beriladi)
    eskiz-from: "4546"
app:
  payments:
    click:
      redirect-base: "https://payments.local/click"
      secret: "click_secret"
    payme:
      redirect-base: "https://payments.local/payme"
      secret: "payme_secret"
    alif:
      redirect-base: "https://payments.local/alif"
      secret: "alif_secret"
    xazna:
      redirect-base: "https://payments.local/xazna"
      secret: "xazna_secret"
    paynet:
      redirect-base: "https://payments.local/paynet"
      secret: "paynet_secret"
    uzum:
      redirect-base: "https://payments.local/uzum"
      secret: "uzum_secret"

